name: json_serializable_converter
description: Easily convert common Dart data types into a json compatible for package:json_serializable.
version: 0.0.1
#publish_to: https://pub.dev
homepage: https://github.com/wittyneko/json_serializable_converter
repository: https://github.com/wittyneko/json_serializable_converter


environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.5.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

